name: Tests

on: [push, pull_request]

jobs:
  tests:
    name: Tests PHP ${{ matrix.php }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        php: [8.1, 8.2, 8.3]
        experimental: [false]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Install dependencies with Composer
        uses: ramsey/composer-install@v1

      - name: Coding standards
        run: composer test:cs

      - name: Static analysis
        run: composer test:stan

      - name: Unit tests
        run: composer test:unit

      - name: Coverage Report
        uses: lucassabreu/comment-coverage-clover@main
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          file: build/phpunit/clover.xml
        if: github.event_name == 'pull_request'
